# version: "3.8"
# services:
#   events:
#     build: ../conference_app_events
#     depends_on:
#       - mongodb
#       - rabbitmq
#     environment:
#       - DB_URI=mongodb+srv://admin:hr-microservices-events@events-microservice.tb5qj.mongodb.net/test?retryWrites=true&w=majority
#       - DB_NAME=development
#       - RABBIT_HOST=rabbitmq
#       - LOCATIONS_URI=http://localhost:8082
#     ports:
#       - "8081:8080"
#     restart: always
#   locations:
#     build: ./locations
#     depends_on:
#       - mongodb
#       - rabbitmq
#     environment:
#       - MONGODB_URI=mongodb://mongodb:27017/locations-dev
#       - RABBITMQ_URI=amqp://rabbitmq
#     ports:
#       - "8082:8000"
#     restart: always
#   # INFRASTRUCTURE
#   postgresql:
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#     image: postgres:13
#     ports:
#       - "5432:5432"
#     restart: always
#     volumes:
#       - ./data/pg_data:/var/lib/postgresql/data
#   mongodb:
#     image: mongo:4.4
#     ports:
#       - "27017:27017"
#     restart: always
#     volumes:
#       - ./data/mongo_data:/data/db
#   rabbitmq:
#     image: "rabbitmq:3"
#     ports:
#       - "5672:5672"